### ISSUE TITLE
Using the plug in

### ISSUE THREAD

**Issue by michaelliesenberg** [dept2/Poppler-QML-plugin#1]
Hi,

i open the Poppler-QML-plugin in Qt creator and build it with no errors.
How do i use the plug in?
If i include it like this #include <poppler-qt5.h>  i get an error: "no such file or directory"

**Comment by michaelliesenberg** [comment]
sorry just saw that the build wasnt successfull.
I get an error that the lirbary cannot be found: unix|win32: LIBS += -lpoppler-qt5
I did "sudo apt install libpoppler-qt5-dev" but still got the error. Any idea?

**Comment by cyberbobs** [comment]
In Ubuntu 16.04 LTS installing `libpoppler-qt5-dev` and `libpoppler-qt5-1` should be sufficient for you to build the plugin. Do you use Qt from system repositories or you have it installed from official installer downloaded from [qt.io](http://qt.io/)?

**Comment by michaelliesenberg** [comment]
Hi cybebobs,
its installed from repositiories.
So i think i didnt had priviledges on make install.
So i open the terminal and on the Poppler-QML-plugin directory i did:
qmake
make
sudo make install
and it made without any errors.
Now a stupid question how do i use your plugin in my QT project?

**Comment by michaelliesenberg** [comment]
Hi cybebobs,
i add a "popplerPlugin" directory at /work/qt5/sysroot/usr/local/qt5.5.1/imports/
and inside there i paste the files "libpopplerPlugin.so", "plugins.qmltypes" and "qmldir".
I made a "popplerPlugin" directory also in /work/qt5/sysroot/usr/local/qt5.5.1/plugins 
and inside there i add the "libpopplerPlugin.so" file.
Now on my project application in any qml file i just import the plugin like this:
import popplerPlugin 1.0

**Comment by michaelliesenberg** [comment]
How do i use the plugin now in QML?
I want to view a pdf

**Comment by michaelliesenberg** [comment]
Hi cyberbobs,
so importing the qml plugin into qml didnt work. As i build the project it gave me an error: 
module "popplerPlugin " is not installed

**Comment by cyberbobs** [comment]
Hey, Michael. Two years have passed and I've finally laid my hands on complete plugin and documentation overhaul. It is now fully documented and supplied with an example of fully functional PDF viewer app using the plugin. If there's any questions left, please, let me know.
