### ISSUE TITLE
Plugin installation

### ISSUE THREAD

**Issue by AndreaInverardi** [dept2/Poppler-QML-plugin#5]
Hi,

My setup:
- Ubuntu 19.04
- Poppler-0.82.0 installed
- QtCreator with Qt 5.13.1
- libpoppler-qt5-dev and libpoppler-qt5-1 installed

Copied Poppler-QML-plugin directory in /home/andrea/Qt/ then inside:
qmake
make
make install 
And it showed no error.

If I try to open the inclued example in QtCreator it gives me:
qrc:/main.qml:9 module "org.docviewer.poppler" is not installed

What I'm doing wrong?

Thanks for your support

**Comment by cyberbobs** [comment]
Did you build it with the same version of Qt you're trying to use? That's pretty common problem: the plugin will be installed to the `plugins` directory in Qt version path. Double check the `qmake` version being called in the first step and paths shown on `make install`. If you're using Qt installed from the official installer, run the supplied qmake version from `bin` directory.

**Comment by AndreaInverardi** [comment]
Hi, 
I've builted it with wrong qmake, instead of the official Qt installer qmake. I've solved.
Thanks for your support
