### ISSUE TITLE
Unable to pan left/right when zoomed in

### ISSUE THREAD

**Issue by brentsink** [dept2/Poppler-QML-plugin#6]
When you zoom in on a PDF and it seems to zoom in on the center of the page and not allow you to pan to the left or the right to see the content.  Is there a way to enable this behavior?  Thanks!

**Comment by cyberbobs** [comment]
Yup, that's true. It's a bug and it's not pretty easy to fix because PDFView is based on ListView, which is not really easy to use for 2D scrollable data. This is not currently a problem for my personal use case so I'll probably get back to it some time in the future.

The MRs on this are most certainly welcome :)

**Comment by brentsink** [comment]
Ok. Any suggestions on where to start? Is it possible to change the zoom x-origin to zero? I noticed if I manually call `flick()` I can flick to the right, but can't go left further than the origin of where it zoomed to.

**Comment by brentsink** [comment]
I was able to create a workaround by wrapping `PDFView` in a `Flickable` like so:

```
Flickable {
    id: fl
    anchors.fill: parent
    width: parent.width; height: parent.height
    contentWidth: width * pdfView.zoom
    contentHeight: pdfView.contentItem.height
    clip: true

    PDFView {
        id: pdfView
        width: fl.width * pdfView.zoom;
        height: fl.height
        focus: true
        boundsBehavior: Flickable.StopAtBounds
        path: root.path

        onZoomChanged: {
            notifyLabel.text = qsTr("Zoom: %1%").arg(pdfView.zoom * 100)
            notifyAnimation.start()
        }
    }

    ScrollBar.horizontal: ScrollBar { active: true; visible: true }
    ScrollBar.vertical: ScrollBar { active: true; visible: true }
}
```

It's not perfect, but it will suffice.
