### ISSUE TITLE
Single Page Display Mode

### ISSUE THREAD

**Issue by myself-shivu** [dept2/Poppler-QML-plugin#7]
Is it possible to display one page at a time with fit to screen width or Screen Height
Right now it is in continuous scrolling mode with multiple pages ( pages are one below the other ) 

Thanks

**Comment by cyberbobs** [comment]
Included basic [PDFView](https://github.com/dept2/Poppler-QML-plugin#using-pdfview-qml-component) component doesn't allow it at the moment.

But you can easily do it yourself: the [Poppler](https://github.com/dept2/Poppler-QML-plugin#using-poppler-object) object enables you to implement basically any view logic you need and is well documented. You may also consult [PDFView sources](https://github.com/dept2/Poppler-QML-plugin/blob/master/src/PDFView.qml) (it's a pure QML component) to see most of the plugin features examples.
